version: "3.8"

services:

  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 3838@Bismillah
      POSTGRES_DB: supplify

    ports:
      - "5433:5432"

    networks:
      - app-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    restart: unless-stopped

    ports:
      - "9092:9092"

    environment:
      # KRaft Mode
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"

      # Controller Configuration
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"

      # Listeners
      KAFKA_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"

      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"

      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"

      # Single Node Settings
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      # Required for KRaft
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"

    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: supplify-backend

    restart: unless-stopped

    depends_on:
      - postgres
      - kafka

    environment:
      SPRING_PROFILES_ACTIVE: docker

      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/supplify
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 3838@Bismillah

      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

    ports:
      - "8080:8080"

    networks:
      - app-network

  frontend:
    build:
      context: ./src/main/webapp/Supplify
      dockerfile: Dockerfile

    container_name: supplify-frontend

    restart: unless-stopped

    depends_on:
      - backend

    ports:
      - "4200:80"

    networks:
      - app-network

networks:
  app-network:
    driver: bridge