spring.application.name=InventoryService

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/supplify
spring.datasource.username=postgres
spring.datasource.password=3838@Bismillah
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.liquibase.enabled=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.liquibase=DEBUG


# Kafka Consumer
spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.group-id=inventory-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.liquibase.change-log=classpath:db/changelog/master.xml