apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: afridshaik3838/supply-backend:1.0
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"

            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/supplify"

            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"

            - name: SPRING_DATASOURCE_PASSWORD
              value: "3838@Bismillah"

            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"