apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend

spec:
  replicas: 1

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend
          image: afridshaik3838/supplify-backend:1.0
          imagePullPolicy: Always

          ports:
            - containerPort: 8080